use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::PathBuf;

const HOOK_SCRIPT: &str = r#"#!/bin/bash
# Auto-generated by rgbpc
rgbpc --sync-theme &
"#;

pub fn get_hook_path() -> PathBuf {
    let mut path = dirs::home_dir().unwrap_or_else(|| PathBuf::from("~"));
    path.push(".config/omarchy/hooks/theme-set");
    path
}

pub fn is_hook_installed() -> bool {
    let path = get_hook_path();
    if let Ok(content) = fs::read_to_string(&path) {
        content.contains("rgbpc --sync-theme")
    } else {
        false
    }
}

pub fn install_hook() -> Result<(), String> {
    let path = get_hook_path();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }

    fs::write(&path, HOOK_SCRIPT).map_err(|e| e.to_string())?;

    // Make executable
    let mut perms = fs::metadata(&path)
        .map_err(|e| e.to_string())?
        .permissions();
    perms.set_mode(0o755);
    fs::set_permissions(&path, perms).map_err(|e| e.to_string())?;

    Ok(())
}

pub fn remove_hook() -> Result<(), String> {
    let path = get_hook_path();
    if path.exists() {
        fs::remove_file(path).map_err(|e| e.to_string())?;
    }
    Ok(())
}
